# Generated by Django 3.1.2 on 2020-10-31 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('members', models.CharField(max_length=60)),
                ('tag', models.CharField(max_length=10)),
                ('wav', models.FileField(upload_to='')),
            ],
        ),
    ]
